### ISSUE TITLE
If we can have debug mode in `/metrics` api?

### ISSUE THREAD

**Issue by JaredTan95** [openinsight-proj/elastic-alert#28]
If we can have debug mode in `/metrics` api?

if `debug` mode actived, metrics would be like this:

```bash
# HELP elastic_alert_hits Show hits/matched number for each rule query
# TYPE elastic_alert_hits gauge
elastic_alert_hits{index="insight-es-k8s-logs-alias",query_string="", bool_query="{"query_string":{"query":"log:error"}},{"range":{"time":{"format":"strict_date_optional_time","gte":"2023-11-28T18:11:42.404101Z","lte":"2023-11-28T18:21:42.404101Z"}}}]}", unique_id="log-error"} 125
```

otherwise, metrics would bot display query details:

```bash
# HELP elastic_alert_hits Show hits/matched number for each rule query
# TYPE elastic_alert_hits gauge
elastic_alert_hits{index="insight-es-k8s-logs-alias", unique_id="log-error"} 125
```

maybe this cloud be in followed PR, and could be implated another way~

_Originally posted by @JaredTan95 in https://github.com/openinsight-proj/elastic-alert/issues/27#issuecomment-1832994142_

**Comment by Frapschen** [comment]
enhance by https://github.com/openinsight-proj/elastic-alert/pull/27
